function doSomething(value) {
  return new Promise((resolve, reject) => {
    reject(value)
  })
}

// ---

doSomething(27)
  .then(value => {
    console.log('Result:', value)        // ніколи не викличеться
  }, reason => {
    console.error('Error:', reason)      // 27
    return 'recovered!'                  // відновлюємо проміс
  })
  .then(value => {
    console.log('Result:', value)        // 'recovered!'
  }, reason => {
    console.error'Error:', error)        // помилки не буде
  })
